### ISSUE TITLE
"cannot load such file -- highline" after upgraded.

### ISSUE THREAD

**Issue by nicknameyu** [chef-cookbooks/chef_client_updater#211] opened 2020-08-13 20:47 UTC
I'm managing thousands of chef-clients. A recent chef upgrade was done by chef_client_updater version3.10.1 and the upgrade target is Chef 16.1.16. 
Many Linux servers failed checking in to Chef after the upgrade. Found below logs in Chef client.log on these Linux servers.
```
[2020-08-13T08:44:24+00:00] INFO: Forking chef instance to converge...
[2020-08-13T08:44:24+00:00] ERROR: cannot load such file -- highline
[2020-08-13T08:44:24+00:00] ERROR: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
chef-client on these linux servers are active. 
Manually running "chef-client" command is successful. 
Anyone can help?

**Comment by Nirbhay1997** [comment] 2020-09-07 12:56
Hey @nicknameyu , Can you please lend me more details (OS, Attribute file, or any other relevant detail ) as everything is working fine at my end.

**Comment by nicknameyu** [comment] 2020-09-07 19:18
Chef ticket was opened. Waiting for investigation

**Comment by Nirbhay1997** [comment] 2020-09-09 13:58
> Chef ticket was opened. Waiting for investigation

Can you please share the details of the ticket created against this issue.?
Also, it would be great if you share any relevant information that may help in reproducing the issue.

**Comment by Nirbhay1997** [comment] 2020-09-11 12:09
@nicknameyu 
Tried running the cookbook(on chef-client 15 as well as 16) on centos 7.8 and Ubuntu 18.04 with update target including 16.1.16 and the latest but no error related to Highline is traceable.

**Comment by nicknameyu** [comment] 2020-09-11 13:03
> > Chef ticket was opened. Waiting for investigation
> 
> Can you please share the details of the ticket created against this issue.?
> Also, it would be great if you share any relevant information that may help in reproducing the issue.
Chef ticket: 25873

**Comment by nicknameyu** [comment] 2020-09-11 13:06
> Tried running the cookbook(on chef-client 15 as well as 16) on centos 7.8 and Ubuntu 18.04 with update target including 16.1.16 and the latest but no error related to Highline is traceable.

I couldn't stably recreate the problem either. But there were hundreds of servers impacted. Some RHEL7, some Ubuntu 1604. Not yet seen it on other OS versions, cause we don't have too many of other Linux Versions.

**Comment by dheerajd-msys** [comment] 2020-12-10 13:52
Tried from my end to reproduce the issue on Ubuntu and Rhel7 with latest version of the cookbook but issue is not getting reproduced.
@nicknameyu could you please share some environmental details like some other cookbooks you are using prior to running this updater cookbook which might have impact on the following execution?

**Comment by dheerajd-msys** [comment] 2020-12-14 07:38
@nicknameyu Based on the ticket created against this issue per your comment https://github.com/chef-cookbooks/chef_client_updater/issues/211#issuecomment-691082262 i.e. ticket [25873](https://getchef.zendesk.com/agent/tickets/25873)

and comment on the same ticket  ```Dina worked with the customer to recreate their issue. Their issues seem to be environmental as not even they can reproduce it (and neither can we)``` it seems the issue is only environmental and not the cookbook issue so closing this for now.

Please feel free to revert if any issue impact you regd this cookbook.

Thanks!!

**Closed by dheerajd-msys** 2020-12-14 07:38 UTC
