### ISSUE TITLE
chef-client scheduled task gets deleted

### ISSUE THREAD

**Issue by mhugley** [chef-cookbooks/chef_client_updater#121] opened 2018-06-08 16:48 UTC
### Cookbook version
3.3.4

### Chef-client version
13.9.1

### Platform Details
Windows 2016 and Windows 2008r2

### Scenario:
Server running chef-client 13.9.1 with scheduled task and when adding chef-client-updater to the run_list and runs and works but deletes the chef-client scheduled task

### Steps to Reproduce:
Create Windows Server with chef-clinet 13.9.1 and add chef-client-updater to the run_list

### Expected Result:
To see the chef-client scheduled task to remain in the list.

### Actual Result:
Scheduled task gets deleted.

**Comment by jjustice6** [comment] 2018-07-23 16:07
This is due to the .MSI file.

The update process looks for a task with that name and deletes it. See:
https://github.com/chef/chef/blob/a3ffe453522b33165c3553097fffeedf705d07f5/omnibus/resources/chef/msi/source.wxs.erb#L108-L110
and
https://github.com/chef/chef/blob/a3ffe453522b33165c3553097fffeedf705d07f5/omnibus/resources/chef/msi/source.wxs.erb#L86-L91
for the responsible code.

You can get around this by naming your scheduled task something else.

**Comment by Happycoil** [comment] 2018-08-22 11:53
If you configure the chef-client task in the same run list you can also use `post_install_action "exec"`. This means the upgrade script will run chef-client when it's done, which in turn recreates the task.

**Comment by jjustice6** [comment] 2018-08-22 14:06
Note that you can only do that in certain situations, otherwise Chef will forcibly change `exec` to `kill`: https://github.com/chef-cookbooks/chef_client_updater/blob/v3.4.2/providers/default.rb#L167-L179

**Comment by nweddle** [comment] 2018-08-23 01:16
@jjustice6 We're seeing this behavior as well with Windows. We're always forced to `kill` which does not seem to jive with the README any longer:
> On Windows, the recommended post_install_action is exec instead of kill if you intend to run Chef periodically. 

@Happycoil The scheduled task being deleted by the client MSI installer is the `chef-client` scheduled task, that our team is managing that with the `chef-client` cookbook. We're expecting it to survive the upgrade so that chef-client will be executed again after our usual interval.

To address this as a workaround, we're creating net new scheduled task that executes chef-client only once twenty minutes after creation. This should be ample time to allow the upgrade to complete.

```ruby
windows_task 'chef-client-once-' + node['chef_client_updater']['version'] do
  frequency :once
  start_time (Time.now + 18 * 60).strftime('%H:%M')
  run_level :highest
  cwd 'C:\\opscode\\chef\\bin'
  command 'chef-client -L C:\\windows\\temp\\chef_client_' + node['chef_client_updater']['version'] + '.log'
  not_if { Chef::VersionConstraint.new(">= #{node['chef_client_updater']['version']}").include?(node['chef_packages']['chef']['version']) }
end
```

The fix I see here is either adding support for `exec` back for Windows, or placing some logic in the `client_updater_cookbook` so that we can control the MSI installer's ChefSchTaskFeature option.

**Comment by Happycoil** [comment] 2018-08-23 05:38
@nweddle what I'm saying is if you set post_install_action to exec now and the chef-client cookbook (or your own custom task creation recipe) is in the run list the task will be recreated. The code is convoluted, but it adds an execution of chef-client to the end of the upgrade script _before_ post_install_action is set back to kill.

**Comment by nweddle** [comment] 2018-08-25 00:39
@Happycoil Thank you for checking my assumptions! 👍 You are completely correct. After switching to `exec` for our Windows nodes, we're seeing the expected behavior.

Seeing
> forcing "exec" to "kill" on windows.
logged in the chef-client output was a red-herring. Combining that with the opaque code logic for Windows, along with a README that could use some clarification, all led to us creating a completely unnecessary scheduled task. 😄 Thanks again.

**Comment by dheerajd-msys** [comment] 2019-12-21 14:39
It seems we've fixed this issue in https://github.com/chef-cookbooks/chef_client_updater/pull/148 .
Closing this issue.

**Closed by dheerajd-msys** 2019-12-21 14:39 UTC
