### ISSUE TITLE
Use smarter default for post_install_action

### ISSUE THREAD

**Issue by wjordan** [chef-cookbooks/chef_client_updater#79] opened 2017-11-28 20:04 UTC
`post_install_action` should just 'do the right thing' by default, rather than require the user to manually choose between `exec` or `kill` settings depending on their use-case.

I saw that the default `post_install_action` was switched from `exec` to `kill` in major-version 3 of this cookbook (#49), to address an issue (#45) that arises from the most common use-case when chef-client runs via forked processes using the `--interval` option.

In that discussion, @tas50 wondered in a [comment](https://github.com/chef-cookbooks/chef_client_updater/issues/45#issuecomment-312028394),

> I wonder if we could make it smarter about just doing the right thing.

You _can_ make it smarter. In my own testing, the 'right thing' is to set the default to `kill` when running via forked process using the `--interval` option (in which case `Chef::Config[:interval]` is present), and `exec` otherwise. I had an implementation of this back in chef-boneyard/omnibus_updater#105, see the following [code](https://github.com/wjordan/omnibus_updater/blob/3fee5dda5a8deb323c81cfb6ed027e8d2ab87614/attributes/default.rb#L27-L30):

```
# Default to 'kill' for long-running, interval-based chef-client
# Default to 'exec' for local-mode and single-run chef-client
default[:omnibus_updater][:upgrade_behavior] =
  Chef::Config[:interval] ? 'kill' : 'exec'
```

Setting a smarter default with this logic should cover most edge-cases including test-kitchen runs.

**Comment by iennae** [comment] 2017-11-29 04:42
@tas50 @lamont-granquist thoughts on this issue?

**Comment by lamont-granquist** [comment] 2018-02-08 22:52
the problem is that even when we do not run with interval mode we still tend to create the supervisor process and fork off a child process to do the work.

for example, when running chef-client from the command line you actually get two process.  this is all likely overly complicated and poor, but the locking conditions, particularly in buggy chef 11-era versions, will still crop up if you try to `exec` with the supervisor process running.  i'm fairly sure that `chef-client --no-fork` avoids the creation of the supervisor.

so you could check that chef-client is both not running in interval mode and is running no_fork and then switch to exec.  and you have to check both because we used to support non-forking interval runs before 12, you can't only check no_fork.

but then the use case becomes a lot more limited since mostly nothing invokes chef-client with `--no-fork` afaik, and this won't fix anyone's test-kitchen runs.

i think we're long past time to fix that behavior at which point this does get more useful:

https://github.com/chef/chef/issues/6712

but it does need to check no_fork correctly.

**Comment by lamont-granquist** [comment] 2018-02-08 22:56
(or i guess interval runs don't matter and its only no_fork that matters?)

**Closed** 2018-03-16 18:31 UTC
